GitlabCIMultiRunner:
  image: ludx/gitlab-ci-java8-runner:1.1.4-3
  volumes:
    - /srv/docker/gitlab-runner:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=
    - RUNNER_TOKEN=
    - RUNNER_DESCRIPTION=
    - RUNNER_EXECUTOR=shell
  restart: always
